
export const productListing = [
    {
    id : 1,
    name : "Frosted White Plastic Bottle 400ml",
    des :"Egestas fringilla eu pellentesque phasellus",
    deepdes : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    rate : 499,
    image :"/src/images/babywithbottlenew.jpg", 
    qty : 1 ,
   },
    {
    id : 2,
    name : "Colorful Birdies on Orange Bandana",
    des : "Girls Newborn & Infant Crimson/Heather Gray Oklahoma Sooners All The Love Bodysuit Bib & Booties Set",
    deepdes : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    rate : 359,
    image:"/src/images/babywithtowelnew.jpg",
    qty : 1 ,
   },
    {
    id : 3,
    name : "Nutrikids Food Nutrition DHA+ Orange",
    des : "Grandpa Is My Bestie Organic Cotton Bodysuit",
    deepdes :"Slip your little one into this Too Much Love set for an adorable dose of Detroit Lions spirit.",
    rate : 899,
    image:"/src/images/nutrikidsnew.jpg",
    qty : 1 ,
   },
    {
    id : 4,
    name : "Extra Soft Touch Lamb Doll",
    des : "Newborn and Infant Black/Gray Baltimore Orioles Game Nap Teddy Fleece Bunting Full-Zip Sleeper",
    deepdes :"Start off your little one's Utah Jazz fandom in historical fashion with this Hardwood Classics Name and Number bodysuit from Mitchell &amp; Ness.",
    rate : 990,
    image:"/src/images/teddynew.jpg",
    qty : 1 ,
   },
    {
    id : 5,
    name : "Teddy Bear Ready To Flight Doll",
    des : "Newborn & Infant Aqua/Orange Miami Dolphins Little Champ Three-Piece Bodysuit Bib & Booties Set",
    deepdes :"Start off your little one's Utah Jazz fandom in historical fashion with this Hardwood Classics Name and Number bodysuit from Mitchell &amp; Ness.",
    rate : 999,
    image:"/src/images/teddyspecsnew.jpg",
    qty : 1 ,
   },
    {
    id : 6,
    name : "Twin Cute Bunny Set Combo",
    des : "Newborn and Infant Royal/Gray Texas Rangers Game Nap Teddy Fleece Bunting Full-Zip Sleeper",
    deepdes : "Let your little champ show off their blossoming Washington Commanders fandom in this adorable set.",
    rate : 1290,
    image:"/src/images/twobabynew.jpg",
    qty : 1 ,
   },
    {
    id : 7,
    name : "VitCom Nutrition Fruits Flavor",
    des : "Starter 2-Way Long Sleeve Swaddle & Head Wrap Set (Baby)",
    deepdes :"Everyone will Scream and Shout when they see your little one in one of these adorable Oakland Athletics bodysuits.",
    rate : 1499,
    image:"/src/images/vitcomnew.jpg",
    qty : 1 ,
   },
    {
    id : 8,
    name : "Sunny Outdoor Picnic Set Yellow",
    des : "Newborn & Infant Black/Heathered Gray Las Vegas Raiders Born To Win Two-Pack Long Sleeve Bodysuit Set",
    deepdes :"Start your youngster down the path of a die-hard Seattle Kraken fan by grabbing this Dream Team hat, pants and bodysuit set.",
    rate : 999,
    image:"/src/images/yellowbabynew.jpg",
    qty : 1 ,
   }
]